---

# Packages main file

  - include: minimal.yml
    sudo: yes
    tags: minimal

  - include: golang.yml
    sudo: yes
    tags: golang

  - include: nginx.yml
    sudo: yes
    tags: nginx

  - include: aws-cli.yml
    sudo: yes
    tags: aws-cli