---

# Install common packages

- name: Install common software
  apt: name={{ item }} state=installed
  with_items:
    - mc
    - htop
    - sysv-rc-conf
    - git
    - bash-completion
    - curl
    - software-properties-common
    - python-software-properties
    - supervisor
    - strace
    - ncdu