---

# common.nginx
# Install nginx from PPA nginx/stable

# Remove apache2
- name: Remove apache2 if installed
  apt: name=apache2 state=absent
  tags: [nginx, rm-apache, packages]

# Install Nginx from PPA Repo
- name: Add nginx/stable PPA
  apt_repository: repo='ppa:nginx/stable'
  tags: [nginx, packages]

- name: Install nginx from PPA
  apt: name=nginx state=present update_cache=yes
  tags: [nginx, packages]