---

# Create users

  - name: Создание пользователей
    sudo: yes
    user:
      name={{ item }}
      shell="/bin/bash"
    with_items:
      - "{{ users }}"
    tags: [users]

  - name: Allow users to use passwordless sudo
    sudo: yes
    template: src=sudoers.j2 dest=/etc/sudoers.d/{{ item }} mode=0440
    with_items:
      - "{{ users }}"
    tags: [users, sudoers]